// <auto-generated />
using System;
using MeetingReservationApp.Data.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeetingReservationApp.Data.Migrations
{
    [DbContext(typeof(MeetingReservationAppContext))]
    partial class MeetingReservationAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InventoryPurpose")
                        .HasColumnType("int");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 488, DateTimeKind.Local).AddTicks(2619),
                            InventoryPurpose = 2,
                            IsFixed = true,
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 488, DateTimeKind.Local).AddTicks(2636),
                            Name = "Beamer",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 488, DateTimeKind.Local).AddTicks(2648),
                            InventoryPurpose = 1,
                            IsFixed = true,
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 488, DateTimeKind.Local).AddTicks(2650),
                            Name = "WhiteBoard",
                            RoomId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 488, DateTimeKind.Local).AddTicks(2654),
                            InventoryPurpose = 2,
                            IsFixed = false,
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 488, DateTimeKind.Local).AddTicks(2656),
                            Name = "Television",
                            RoomId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 488, DateTimeKind.Local).AddTicks(2660),
                            InventoryPurpose = 1,
                            IsFixed = true,
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 488, DateTimeKind.Local).AddTicks(2661),
                            Name = "WhiteBoard",
                            RoomId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 488, DateTimeKind.Local).AddTicks(2666),
                            InventoryPurpose = 3,
                            IsFixed = true,
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 488, DateTimeKind.Local).AddTicks(2667),
                            Name = "Video Conference Equipment",
                            RoomId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 488, DateTimeKind.Local).AddTicks(2671),
                            InventoryPurpose = 2,
                            IsFixed = false,
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 488, DateTimeKind.Local).AddTicks(2672),
                            Name = "Television",
                            RoomId = 5
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 488, DateTimeKind.Local).AddTicks(2677),
                            InventoryPurpose = 3,
                            IsFixed = true,
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 488, DateTimeKind.Local).AddTicks(2678),
                            Name = "Television",
                            RoomId = 5
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 488, DateTimeKind.Local).AddTicks(2682),
                            InventoryPurpose = 2,
                            IsFixed = true,
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 488, DateTimeKind.Local).AddTicks(2684),
                            Name = "Beamer",
                            RoomId = 6
                        });
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.InventoryReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoomReservationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("RoomReservationGuid");

                    b.ToTable("InventoryReservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 498, DateTimeKind.Local).AddTicks(4416),
                            InventoryId = 2,
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 498, DateTimeKind.Local).AddTicks(4435),
                            RoomReservationGuid = new Guid("019ee26d-5111-4d96-abfa-5bd6c966d529")
                        });
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OfficeEndHours")
                        .HasColumnType("int");

                    b.Property<int>("OfficeEndMinutes")
                        .HasColumnType("int");

                    b.Property<int>("OfficeStartHours")
                        .HasColumnType("int");

                    b.Property<int>("OfficeStartMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 479, DateTimeKind.Local).AddTicks(2897),
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 479, DateTimeKind.Local).AddTicks(3283),
                            Name = "Amsterdam",
                            OfficeEndHours = 17,
                            OfficeEndMinutes = 0,
                            OfficeStartHours = 8,
                            OfficeStartMinutes = 30
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 479, DateTimeKind.Local).AddTicks(3655),
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 479, DateTimeKind.Local).AddTicks(3657),
                            Name = "Berlin",
                            OfficeEndHours = 20,
                            OfficeEndMinutes = 0,
                            OfficeStartHours = 8,
                            OfficeStartMinutes = 30
                        });
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttendanceCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasChairs")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendanceCapacity = 10,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 485, DateTimeKind.Local).AddTicks(4866),
                            HasChairs = true,
                            LocationId = 1,
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 485, DateTimeKind.Local).AddTicks(4886),
                            Name = "Meeting Room 1"
                        },
                        new
                        {
                            Id = 2,
                            AttendanceCapacity = 12,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 485, DateTimeKind.Local).AddTicks(4899),
                            HasChairs = true,
                            LocationId = 1,
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 485, DateTimeKind.Local).AddTicks(4900),
                            Name = "Meeting Room 2"
                        },
                        new
                        {
                            Id = 3,
                            AttendanceCapacity = 5,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 485, DateTimeKind.Local).AddTicks(4905),
                            HasChairs = false,
                            LocationId = 1,
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 485, DateTimeKind.Local).AddTicks(4906),
                            Name = "Meeting Room 3"
                        },
                        new
                        {
                            Id = 4,
                            AttendanceCapacity = 20,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 485, DateTimeKind.Local).AddTicks(4911),
                            HasChairs = true,
                            LocationId = 2,
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 485, DateTimeKind.Local).AddTicks(4912),
                            Name = "Meeting Room A"
                        },
                        new
                        {
                            Id = 5,
                            AttendanceCapacity = 5,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 485, DateTimeKind.Local).AddTicks(4916),
                            HasChairs = false,
                            LocationId = 2,
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 485, DateTimeKind.Local).AddTicks(4918),
                            Name = "Meeting Room B"
                        },
                        new
                        {
                            Id = 6,
                            AttendanceCapacity = 25,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 485, DateTimeKind.Local).AddTicks(4922),
                            HasChairs = true,
                            LocationId = 2,
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 485, DateTimeKind.Local).AddTicks(4923),
                            Name = "Meeting Room C"
                        });
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.RoomReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttendantCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("MeetingEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MeetingStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomReservationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomReservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendantCount = 7,
                            CreatedDate = new DateTime(2021, 10, 10, 1, 7, 28, 491, DateTimeKind.Local).AddTicks(174),
                            Description = "Marketing Unit Meeting",
                            MeetingEndTime = new DateTime(2021, 10, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MeetingStartTime = new DateTime(2021, 10, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 10, 10, 1, 7, 28, 491, DateTimeKind.Local).AddTicks(192),
                            RoomId = 2,
                            RoomReservationGuid = new Guid("019ee26d-5111-4d96-abfa-5bd6c966d529")
                        });
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.Inventory", b =>
                {
                    b.HasOne("MeetingReservationApp.Entities.Concrete.Room", "Room")
                        .WithMany("Inventories")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.InventoryReservation", b =>
                {
                    b.HasOne("MeetingReservationApp.Entities.Concrete.Inventory", "Inventory")
                        .WithMany("InventoryReservations")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MeetingReservationApp.Entities.Concrete.RoomReservation", "RoomReservation")
                        .WithMany("InventoryReservations")
                        .HasForeignKey("RoomReservationGuid")
                        .HasPrincipalKey("RoomReservationGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("RoomReservation");
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.Room", b =>
                {
                    b.HasOne("MeetingReservationApp.Entities.Concrete.Location", "Location")
                        .WithMany("Rooms")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.RoomReservation", b =>
                {
                    b.HasOne("MeetingReservationApp.Entities.Concrete.Room", "Room")
                        .WithMany("RoomReservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.Inventory", b =>
                {
                    b.Navigation("InventoryReservations");
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.Location", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.Room", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("RoomReservations");
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.RoomReservation", b =>
                {
                    b.Navigation("InventoryReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
