// <auto-generated />
using System;
using MeetingReservationApp.Data.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeetingReservationApp.Data.Migrations
{
    [DbContext(typeof(MeetingReservationAppContext))]
    partial class MeetingReservationAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InventoryPurpose")
                        .HasColumnType("int");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 569, DateTimeKind.Local).AddTicks(7831),
                            InventoryPurpose = 2,
                            IsFixed = true,
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 569, DateTimeKind.Local).AddTicks(7845),
                            Name = "Beamer",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 569, DateTimeKind.Local).AddTicks(7855),
                            InventoryPurpose = 1,
                            IsFixed = true,
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 569, DateTimeKind.Local).AddTicks(7856),
                            Name = "WhiteBoard",
                            RoomId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 569, DateTimeKind.Local).AddTicks(7859),
                            InventoryPurpose = 2,
                            IsFixed = false,
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 569, DateTimeKind.Local).AddTicks(7860),
                            Name = "Television",
                            RoomId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 569, DateTimeKind.Local).AddTicks(7863),
                            InventoryPurpose = 1,
                            IsFixed = true,
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 569, DateTimeKind.Local).AddTicks(7864),
                            Name = "WhiteBoard",
                            RoomId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 569, DateTimeKind.Local).AddTicks(7868),
                            InventoryPurpose = 3,
                            IsFixed = true,
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 569, DateTimeKind.Local).AddTicks(7869),
                            Name = "Video Conference Equipment",
                            RoomId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 569, DateTimeKind.Local).AddTicks(7872),
                            InventoryPurpose = 2,
                            IsFixed = false,
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 569, DateTimeKind.Local).AddTicks(7873),
                            Name = "Television",
                            RoomId = 5
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 569, DateTimeKind.Local).AddTicks(7876),
                            InventoryPurpose = 3,
                            IsFixed = true,
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 569, DateTimeKind.Local).AddTicks(7877),
                            Name = "Television",
                            RoomId = 5
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 569, DateTimeKind.Local).AddTicks(7880),
                            InventoryPurpose = 2,
                            IsFixed = true,
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 569, DateTimeKind.Local).AddTicks(7881),
                            Name = "Beamer",
                            RoomId = 6
                        });
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.InventoryReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoomReservationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoomReservationGuid");

                    b.ToTable("InventoryReservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 576, DateTimeKind.Local).AddTicks(9454),
                            InventoryId = 2,
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 576, DateTimeKind.Local).AddTicks(9467),
                            RoomReservationGuid = new Guid("019ee26d-5111-4d96-abfa-5bd6c966d529")
                        });
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OfficeEndHours")
                        .HasColumnType("int");

                    b.Property<int>("OfficeEndMinutes")
                        .HasColumnType("int");

                    b.Property<int>("OfficeStartHours")
                        .HasColumnType("int");

                    b.Property<int>("OfficeStartMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 563, DateTimeKind.Local).AddTicks(2926),
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 563, DateTimeKind.Local).AddTicks(3186),
                            Name = "Amsterdam",
                            OfficeEndHours = 17,
                            OfficeEndMinutes = 0,
                            OfficeStartHours = 8,
                            OfficeStartMinutes = 30
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 563, DateTimeKind.Local).AddTicks(3436),
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 563, DateTimeKind.Local).AddTicks(3438),
                            Name = "Berlin",
                            OfficeEndHours = 20,
                            OfficeEndMinutes = 0,
                            OfficeStartHours = 8,
                            OfficeStartMinutes = 30
                        });
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttendanceCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasChairs")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendanceCapacity = 10,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 567, DateTimeKind.Local).AddTicks(6987),
                            HasChairs = true,
                            LocationId = 1,
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 567, DateTimeKind.Local).AddTicks(7001),
                            Name = "Meeting Room 1"
                        },
                        new
                        {
                            Id = 2,
                            AttendanceCapacity = 12,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 567, DateTimeKind.Local).AddTicks(7009),
                            HasChairs = true,
                            LocationId = 1,
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 567, DateTimeKind.Local).AddTicks(7011),
                            Name = "Meeting Room 2"
                        },
                        new
                        {
                            Id = 3,
                            AttendanceCapacity = 5,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 567, DateTimeKind.Local).AddTicks(7014),
                            HasChairs = false,
                            LocationId = 1,
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 567, DateTimeKind.Local).AddTicks(7015),
                            Name = "Meeting Room 3"
                        },
                        new
                        {
                            Id = 4,
                            AttendanceCapacity = 20,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 567, DateTimeKind.Local).AddTicks(7018),
                            HasChairs = true,
                            LocationId = 2,
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 567, DateTimeKind.Local).AddTicks(7019),
                            Name = "Meeting Room A"
                        },
                        new
                        {
                            Id = 5,
                            AttendanceCapacity = 5,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 567, DateTimeKind.Local).AddTicks(7023),
                            HasChairs = false,
                            LocationId = 2,
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 567, DateTimeKind.Local).AddTicks(7024),
                            Name = "Meeting Room B"
                        },
                        new
                        {
                            Id = 6,
                            AttendanceCapacity = 25,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 567, DateTimeKind.Local).AddTicks(7027),
                            HasChairs = true,
                            LocationId = 2,
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 567, DateTimeKind.Local).AddTicks(7028),
                            Name = "Meeting Room C"
                        });
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.RoomReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttendantCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("MeetingEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MeetingStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomReservationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoomReservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendantCount = 7,
                            CreatedDate = new DateTime(2021, 10, 7, 0, 12, 56, 571, DateTimeKind.Local).AddTicks(2147),
                            Description = "Marketing Unit Meeting",
                            MeetingEndTime = new DateTime(2021, 10, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MeetingStartTime = new DateTime(2021, 10, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 10, 7, 0, 12, 56, 571, DateTimeKind.Local).AddTicks(2160),
                            RoomId = 2,
                            RoomReservationGuid = new Guid("019ee26d-5111-4d96-abfa-5bd6c966d529")
                        });
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.Inventory", b =>
                {
                    b.HasOne("MeetingReservationApp.Entities.Concrete.Room", "Room")
                        .WithMany("Inventories")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.InventoryReservation", b =>
                {
                    b.HasOne("MeetingReservationApp.Entities.Concrete.RoomReservation", "RoomReservation")
                        .WithMany("InventoryReservation")
                        .HasForeignKey("RoomReservationGuid")
                        .HasPrincipalKey("RoomReservationGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomReservation");
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.Room", b =>
                {
                    b.HasOne("MeetingReservationApp.Entities.Concrete.Location", "Location")
                        .WithMany("Rooms")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.Location", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.Room", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("MeetingReservationApp.Entities.Concrete.RoomReservation", b =>
                {
                    b.Navigation("InventoryReservation");
                });
#pragma warning restore 612, 618
        }
    }
}
